# Generated by Django 4.2.2 on 2023-06-27 07:59

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('EmailAddress', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='FutureEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_photo', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('content_title', ckeditor.fields.RichTextField(blank=True, null=100)),
                ('big_contents', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=500)),
            ],
            options={
                'verbose_name': 'Future_Events',
                'verbose_name_plural': 'Future_Events',
            },
        ),
        migrations.CreateModel(
            name='LatestEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('contente_title', ckeditor.fields.RichTextField(blank=True, null=100)),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=500)),
            ],
            options={
                'verbose_name': 'Lastest_Events',
                'verbose_name_plural': 'Lastest_Events',
            },
        ),
    ]
